
DROP TABLE "G_SERVICES";

CREATE TABLE "G_SERVICES" (
"TABLE_NAME" VARCHAR2(4000 BYTE), 
"TYPE" VARCHAR2(4000 BYTE), 
"FINAL_TABLE" VARCHAR2(4000 BYTE), 
"FIELDS" VARCHAR2(4000 BYTE), 
"KEYS" VARCHAR2(4000 BYTE), 
"SEPARATOR" VARCHAR2(4000 BYTE), 
"SEC_INFO" VARCHAR2(4000 BYTE), 
"RESOLVER" VARCHAR2(4000 BYTE), 
"SEC_RESOLVER" VARCHAR2(4000 BYTE), 
"SELECT_VALUE" VARCHAR2(4000 BYTE), 
"SELECT_FILTER" VARCHAR2(4000 BYTE), 
"INSERT_VALUE" VARCHAR2(4000 BYTE), 
"UPDATE_VALUE" VARCHAR2(4000 BYTE), 
"DELETE_VALUE" VARCHAR2(4000 BYTE)
);

SET DEFINE OFF;
Insert into G_SERVICES (TABLE_NAME,TYPE,FINAL_TABLE,FIELDS,KEYS,SEPARATOR,SEC_INFO,RESOLVER,SEC_RESOLVER,SELECT_VALUE,SELECT_FILTER,INSERT_VALUE,UPDATE_VALUE,DELETE_VALUE) values ('G_SERVICES',null,null,'*','TABLE_NAME',null,null,null,null,null,null,null,null,null);
Insert into G_SERVICES (TABLE_NAME,TYPE,FINAL_TABLE,FIELDS,KEYS,SEPARATOR,SEC_INFO,RESOLVER,SEC_RESOLVER,SELECT_VALUE,SELECT_FILTER,INSERT_VALUE,UPDATE_VALUE,DELETE_VALUE) values ('DATABASE',null,null,'ID#S#SEQ_GENERIC,*','ID',null,'SIUDE=ADMIN',null,null,null,null,null,null,null);
Insert into G_SERVICES (TABLE_NAME,TYPE,FINAL_TABLE,FIELDS,KEYS,SEPARATOR,SEC_INFO,RESOLVER,SEC_RESOLVER,SELECT_VALUE,SELECT_FILTER,INSERT_VALUE,UPDATE_VALUE,DELETE_VALUE) values ('SECCION',null,null,'ID#S#SEQ_GENERIC,*','ID',null,'SIUDE=ADMIN',null,null,null,null,null,null,null);
Insert into G_SERVICES (TABLE_NAME,TYPE,FINAL_TABLE,FIELDS,KEYS,SEPARATOR,SEC_INFO,RESOLVER,SEC_RESOLVER,SELECT_VALUE,SELECT_FILTER,INSERT_VALUE,UPDATE_VALUE,DELETE_VALUE) values ('VIEW_SECCIONES',null,null,'*','ID',null,'SIUDE=ADMIN',null,null,'SELECT DB.FILENAME AS DB_FILENAME, S.* FROM SECCION S LEFT JOIN DATABASE DB ON (S.ID_DB=DB.ID)','WHERE DB.ID=#{user.attr.DATABASE.ID}',null,null,null);
Insert into G_SERVICES (TABLE_NAME,TYPE,FINAL_TABLE,FIELDS,KEYS,SEPARATOR,SEC_INFO,RESOLVER,SEC_RESOLVER,SELECT_VALUE,SELECT_FILTER,INSERT_VALUE,UPDATE_VALUE,DELETE_VALUE) values ('VIEW_MODELOS',null,null,'*','ID',null,'SIUDE=ADMIN',null,null,'SELECT DB.FILENAME AS DB_FILENAME,M.* FROM MODELO M LEFT JOIN DATABASE DB ON (M.ID_DB=DB.ID)','WHERE DB.ID=#{user.attr.DATABASE.ID}',null,null,null);
Insert into G_SERVICES (TABLE_NAME,TYPE,FINAL_TABLE,FIELDS,KEYS,SEPARATOR,SEC_INFO,RESOLVER,SEC_RESOLVER,SELECT_VALUE,SELECT_FILTER,INSERT_VALUE,UPDATE_VALUE,DELETE_VALUE) values ('MODELO',null,null,'ID#S#SEQ_GENERIC,*','ID',null,'SIUDE=ADMIN',null,null,null,null,null,null,null);
Insert into G_SERVICES (TABLE_NAME,TYPE,FINAL_TABLE,FIELDS,KEYS,SEPARATOR,SEC_INFO,RESOLVER,SEC_RESOLVER,SELECT_VALUE,SELECT_FILTER,INSERT_VALUE,UPDATE_VALUE,DELETE_VALUE) values ('VIEW_MODELO_SECCION',null,null,'*','ID',null,'SIUDE=ADMIN',null,null,'SELECT DB.FILENAME AS DB_FILENAME,MS.*,S.FILENAME AS S_FILENAME,S.DEPENDENCIAS AS S_DEPENDENCIAS FROM MODELO_SECCION MS LEFT JOIN DATABASE DB ON (MS.ID_DB=DB.ID) LEFT JOIN SECCION S ON (MS.ID_SECCION=S.ID AND MS.ID_DB=S.ID_DB)',null,null,null,null);
Insert into G_SERVICES (TABLE_NAME,TYPE,FINAL_TABLE,FIELDS,KEYS,SEPARATOR,SEC_INFO,RESOLVER,SEC_RESOLVER,SELECT_VALUE,SELECT_FILTER,INSERT_VALUE,UPDATE_VALUE,DELETE_VALUE) values ('MODELO_SECCION',null,null,'ID#S#SEQ_GENERIC,*','ID',null,'SIUDE=ADMIN',null,null,null,null,null,null,null);

ALTER TABLE "G_SERVICES" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
